import { config, library } from '@fortawesome/fontawesome-svg-core';
import {
  faDeviantart,
  faDiscord,
  faFacebookSquare,
  faGithub,
  faGuilded,
  faMastodon,
  faOsi,
  faPatreon,
  faPlaystation,
  faSoundcloud,
  faSteam,
  faSteamSymbol,
  faTelegramPlane,
  faTwitter,
  faVk,
  faXbox,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons';
import {
  faArrowRight,
  faBirthdayCake,
  faClipboard,
  faDog,
  faDownload,
  faExclamationTriangle,
  faFileDownload,
  faGlobe,
  faHeart,
  faHome,
  faHorse,
  faHorseHead,
  faIdCard,
  faImage,
  faImages,
  faLeaf,
  faLink,
  faLock,
  faPaintBrush,
  faPalette,
  faPaw,
  faPenNib,
  faPlayCircle,
  faShieldAlt,
  faSpinner,
  faStar,
  faTimes,
  faTrash,
  faUser,
  faVenus,
} from '@fortawesome/free-solid-svg-icons';

// Tell Font Awesome to skip adding the CSS automatically since it's being imported
config.autoAddCss = false;

const brandIcons = [
  faDeviantart,
  faDiscord,
  faFacebookSquare,
  faGithub,
  faGuilded,
  faMastodon,
  faOsi,
  faPatreon,
  faPlaystation,
  faSoundcloud,
  faSteam,
  faSteamSymbol,
  faTelegramPlane,
  faTwitter,
  faXbox,
  faYoutube,
  faVk,
];

// List of used icons - amend if new icons are needed
library.add(
  ...brandIcons,
  faPaw,
  faDog,
  faLeaf,
  faLock,
  faUser,
  faStar,
  faHome,
  faLink,
  faHorse,
  faGlobe,
  faHeart,
  faImage,
  faTimes,
  faVenus,
  faTrash,
  faIdCard,
  faPenNib,
  faImages,
  faPalette,
  faSpinner,
  faDownload,
  faClipboard,
  faHorseHead,
  faShieldAlt,
  faArrowRight,
  faPlayCircle,
  faPaintBrush,
  faFileDownload,
  faBirthdayCake,
  faExclamationTriangle,
);
