import { config, library } from '@fortawesome/fontawesome-svg-core';
import { fab } from '@fortawesome/free-brands-svg-icons';
import {
  faArrowRight,
  faBirthdayCake,
  faClipboard,
  faCompactDisc,
  faDog,
  faDownload,
  faExclamationTriangle,
  faGlobe,
  faHeart,
  faHorse,
  faHorseHead,
  faIdCard,
  faImage,
  faLeaf,
  faLock,
  faPaintBrush,
  faPalette,
  faPaw,
  faPenNib,
  faShieldAlt,
  faStar,
  faTimes,
  faTrash,
  faUser,
  faVenus,
} from '@fortawesome/free-solid-svg-icons';

// Tell Font Awesome to skip adding the CSS automatically since it's being imported
config.autoAddCss = false;

// List of used icons - amend if new icons are needed
library.add(
  fab,
  faPaw,
  faDog,
  faLeaf,
  faLock,
  faUser,
  faStar,
  faHorse,
  faGlobe,
  faHeart,
  faImage,
  faTimes,
  faVenus,
  faTrash,
  faIdCard,
  faPenNib,
  faPalette,
  faDownload,
  faClipboard,
  faHorseHead,
  faShieldAlt,
  faArrowRight,
  faPaintBrush,
  faCompactDisc,
  faBirthdayCake,
  faExclamationTriangle,
);
